# File generated from our OpenAPI spec
defmodule PolarExpress.Schemas.StripeAccountCountry do
  @moduledoc "StripeAccountCountry enum. Possible values: `AL`, `AG`, `AR`, `AM`, `AU`, `AT`, `BH`, `BE`, `BO`, `BA`, `BG`, `KH`, `CA`, `CL`, `CO`, `CR`, `HR`, `CY`, `CZ`, `CI`, `DK`, `DO`, `EC`, `EG`, `SV`, `EE`, `ET`, `FI`, `FR`, `GM`, `DE`, `GH`, `GR`, `GT`, `GY`, `HK`, `HU`, `IS`, `IN`, `ID`, `IE`, `IL`, `IT`, `JM`, `JP`, `JO`, `KE`, `KW`, `LV`, `LI`, `LT`, `LU`, `MO`, `MG`, `MY`, `MT`, `MU`, `MX`, `MD`, `MN`, `MA`, `NA`, `NL`, `NZ`, `NG`, `MK`, `NO`, `OM`, `PA`, `PY`, `PE`, `PH`, `PL`, `PT`, `QA`, `RO`, `RW`, `SA`, `SN`, `RS`, `SG`, `SK`, `SI`, `ZA`, `KR`, `ES`, `LK`, `LC`, `SE`, `CH`, `TZ`, `TH`, `TT`, `TN`, `TR`, `AE`, `GB`, `US`, `UY`, `UZ`, `VN`, `DZ`, `AO`, `AZ`, `BS`, `BD`, `BJ`, `BT`, `BW`, `BN`, `GA`, `KZ`, `LA`, `MC`, `MZ`, `NE`, `PK`, `SM`, `TW`."

  @type t :: String.t()

  @values [
    "AL",
    "AG",
    "AR",
    "AM",
    "AU",
    "AT",
    "BH",
    "BE",
    "BO",
    "BA",
    "BG",
    "KH",
    "CA",
    "CL",
    "CO",
    "CR",
    "HR",
    "CY",
    "CZ",
    "CI",
    "DK",
    "DO",
    "EC",
    "EG",
    "SV",
    "EE",
    "ET",
    "FI",
    "FR",
    "GM",
    "DE",
    "GH",
    "GR",
    "GT",
    "GY",
    "HK",
    "HU",
    "IS",
    "IN",
    "ID",
    "IE",
    "IL",
    "IT",
    "JM",
    "JP",
    "JO",
    "KE",
    "KW",
    "LV",
    "LI",
    "LT",
    "LU",
    "MO",
    "MG",
    "MY",
    "MT",
    "MU",
    "MX",
    "MD",
    "MN",
    "MA",
    "NA",
    "NL",
    "NZ",
    "NG",
    "MK",
    "NO",
    "OM",
    "PA",
    "PY",
    "PE",
    "PH",
    "PL",
    "PT",
    "QA",
    "RO",
    "RW",
    "SA",
    "SN",
    "RS",
    "SG",
    "SK",
    "SI",
    "ZA",
    "KR",
    "ES",
    "LK",
    "LC",
    "SE",
    "CH",
    "TZ",
    "TH",
    "TT",
    "TN",
    "TR",
    "AE",
    "GB",
    "US",
    "UY",
    "UZ",
    "VN",
    "DZ",
    "AO",
    "AZ",
    "BS",
    "BD",
    "BJ",
    "BT",
    "BW",
    "BN",
    "GA",
    "KZ",
    "LA",
    "MC",
    "MZ",
    "NE",
    "PK",
    "SM",
    "TW"
  ]

  @doc "List of valid enum values."
  def values, do: @values

  @schema_name "StripeAccountCountry"
  def schema_name, do: @schema_name
end
